apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: 02tech
  description: The Company - 02tech
spec:
  type: organization
  profile:
    displayName: 02tech
  children: [02.01dx, 02.02cloud]
