apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  description: backstage test teams
  annotations:
    backstage.io/definition-at-location: 'url:https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/spotify.com/v1/swagger.yaml'
  tags:
    - python
    - package
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
spec:
  type: package
  owner: team-a
  lifecycle: experimental
